# This file was generated by GoReleaser. DO NOT EDIT.
cask "szero" do
  name "szero"
  desc "Temporarily scale down all deployments, statefulsets, and daemonsets in a namespace."
  homepage "https://github.com/jadolg/szero"
  version "1.13.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "szero"
  manpage "man/szero.1.gz"
  bash_completion "completions/szero.bash"
  zsh_completion "completions/szero.zsh"
  fish_completion "completions/szero.fish"

  on_macos do
    on_intel do
      url "https://github.com/jadolg/szero/releases/download/v#{version}/szero_darwin_amd64.tar.gz"
      sha256 "2e8985addb5fb415283e889c63ac051a544094dcd1837436682c5e9b058afe4f"
    end
    on_arm do
      url "https://github.com/jadolg/szero/releases/download/v#{version}/szero_darwin_arm64.tar.gz"
      sha256 "f13d515e93ae3ee612fb014cdb5d0a5560a4c0dd050a09e6aed95a386f9475f2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jadolg/szero/releases/download/v#{version}/szero_linux_amd64.tar.gz"
      sha256 "b6ab7199267cc02b9b3c87a6197e1cdc10316f42297791dc45f41130708049f4"
    end
    on_arm do
      url "https://github.com/jadolg/szero/releases/download/v#{version}/szero_linux_arm64.tar.gz"
      sha256 "f2abfd9eb17e1b96f8ebcee7bf49918d4a3abef2f977740bbf11e00801cb848b"
    end
  end

  postflight do
    if OS.mac?
      # Remove quarantine attribute if it exists
      if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
        system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/szero"]
      end
    end
  end

  # No zap stanza required
end
