# This file was generated by GoReleaser. DO NOT EDIT.
cask "szero" do
  name "szero"
  desc "Temporarily scale down all deployments, statefulsets, and daemonsets in a namespace."
  homepage "https://github.com/jadolg/szero"
  version "1.12.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "szero"
  manpage "man/szero.1.gz"
  bash_completion "completions/szero.bash"
  zsh_completion "completions/szero.zsh"
  fish_completion "completions/szero.fish"

  on_macos do
    on_intel do
      url "https://github.com/jadolg/szero/releases/download/v#{version}/szero_darwin_amd64.tar.gz"
      sha256 "a2374c56846fe1cd2c19464baf64fa69aa08f087ad2f4a572e8b8824cffdae3f"
    end
    on_arm do
      url "https://github.com/jadolg/szero/releases/download/v#{version}/szero_darwin_arm64.tar.gz"
      sha256 "4214a96683dc5240dbab1f914642457a5203b6bc545ba59e30f8b0f71af947bb"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jadolg/szero/releases/download/v#{version}/szero_linux_amd64.tar.gz"
      sha256 "27cf91dc7f82e814d0416b9a8feb1e234cdefb48a4a4a49f81f7f6011d5a9db7"
    end
    on_arm do
      url "https://github.com/jadolg/szero/releases/download/v#{version}/szero_linux_arm64.tar.gz"
      sha256 "1c12a44cf47763cc6e15521e325e5d33790c780a03598a4eed2f7a108b63c72a"
    end
  end

  postflight do
    if OS.mac?
      # Remove quarantine attribute if it exists
      if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
        system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/szero"]
      end
    end
  end

  # No zap stanza required
end
