# This file was generated by GoReleaser. DO NOT EDIT.
cask "szero" do
  name "szero"
  desc "Temporarily scale down all deployments, statefulsets, and daemonsets in a namespace."
  homepage "https://github.com/jadolg/szero"
  version "1.14.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "szero"
  manpage "man/szero.1.gz"
  bash_completion "completions/szero.bash"
  zsh_completion "completions/szero.zsh"
  fish_completion "completions/szero.fish"

  on_macos do
    on_intel do
      url "https://github.com/jadolg/szero/releases/download/v#{version}/szero_darwin_amd64.tar.gz"
      sha256 "23bb052a42d603bc6e09bec226ea242327d9cda3f39036616c56532430847a8d"
    end
    on_arm do
      url "https://github.com/jadolg/szero/releases/download/v#{version}/szero_darwin_arm64.tar.gz"
      sha256 "93ddd35ee91af4c577e93284aa12c76269976f19ac1699c7be19244e609e45cc"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jadolg/szero/releases/download/v#{version}/szero_linux_amd64.tar.gz"
      sha256 "e7b44aedd2818221fc03379aa0851bff3390ca48b585ec81641e791b9ba947e0"
    end
    on_arm do
      url "https://github.com/jadolg/szero/releases/download/v#{version}/szero_linux_arm64.tar.gz"
      sha256 "3e175710740c1fcc284923eb7f600bcc249da0cf16888d2aa9582c34cb48bbd8"
    end
  end

  postflight do
    if OS.mac?
      # Remove quarantine attribute if it exists
      if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
        system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/szero"]
      end
    end
  end

  # No zap stanza required
end
