# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class JwtDecode < Formula
  desc "Simple tool to decode JSON Web token."
  homepage "https://github.com/jadolg/jwt-decode"
  version "2.1.2"

  on_macos do
    on_intel do
      url "https://github.com/jadolg/jwt-decode/releases/download/v2.1.2/jwt-decode_Darwin_x86_64.tar.gz"
      sha256 "d73ce468b914f631de3a6681a569af00833d27c2387026a2d261f14bedbde4ef"

      def install
        bin.install "jwt-decode"
      end
    end
    on_arm do
      url "https://github.com/jadolg/jwt-decode/releases/download/v2.1.2/jwt-decode_Darwin_arm64.tar.gz"
      sha256 "58e645e7821bb44d49f15255e05caba95c0e9ddc4ba24f16676266cbdd19deed"

      def install
        bin.install "jwt-decode"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jadolg/jwt-decode/releases/download/v2.1.2/jwt-decode_Linux_x86_64.tar.gz"
        sha256 "35329ea478163b84d1407e24f5ea300b531c30dc3a690f406df520455a09f3cd"

        def install
          bin.install "jwt-decode"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jadolg/jwt-decode/releases/download/v2.1.2/jwt-decode_Linux_arm64.tar.gz"
        sha256 "f175c87b78f174f266ba42bdb1b7ee2496af749f6c385469bde28d705ca78c5f"

        def install
          bin.install "jwt-decode"
        end
      end
    end
  end
end
