# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class JwtDecode < Formula
  desc "Simple tool to decode JSON Web token."
  homepage "https://github.com/jadolg/jwt-decode"
  version "2.1.3"

  on_macos do
    on_intel do
      url "https://github.com/jadolg/jwt-decode/releases/download/v2.1.3/jwt-decode_Darwin_x86_64.tar.gz"
      sha256 "27ac55a5409246ee0190a9c2d433fb7652f147520b7f78296343de131f7dad56"

      def install
        bin.install "jwt-decode"
      end
    end
    on_arm do
      url "https://github.com/jadolg/jwt-decode/releases/download/v2.1.3/jwt-decode_Darwin_arm64.tar.gz"
      sha256 "414168be047be428e143ef4322e431b739cce71bc7da50b40c019d24e499b226"

      def install
        bin.install "jwt-decode"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jadolg/jwt-decode/releases/download/v2.1.3/jwt-decode_Linux_x86_64.tar.gz"
        sha256 "8e36aad7793a39a084d9d6e6382d796b7f6f47e2e76532463bba1c7ed5f56380"

        def install
          bin.install "jwt-decode"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jadolg/jwt-decode/releases/download/v2.1.3/jwt-decode_Linux_arm64.tar.gz"
        sha256 "f4618dbae795ce893aaecfcd2398d8ee6c12d0b0f35300f0fc63488113e2cdb6"

        def install
          bin.install "jwt-decode"
        end
      end
    end
  end
end
