# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Szero < Formula
  desc "Temporarily scale down/up/restart all deployments in a namespace."
  homepage "https://github.com/jadolg/szero"
  version "1.6.3"

  on_macos do
    on_intel do
      url "https://github.com/jadolg/szero/releases/download/v1.6.3/szero_Darwin_x86_64.tar.gz"
      sha256 "b2ae63772f08890dab34248ec86d156cecf457fbded3499c0f22a1cb36de8d24"

      def install
        bin.install "szero"
      end
    end
    on_arm do
      url "https://github.com/jadolg/szero/releases/download/v1.6.3/szero_Darwin_arm64.tar.gz"
      sha256 "166d508a47d911f6e6eba366ca5f3a5564a9ad069f515b408467f4eee1737b80"

      def install
        bin.install "szero"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jadolg/szero/releases/download/v1.6.3/szero_Linux_x86_64.tar.gz"
        sha256 "6b2dbac699d843cb0caf7200451caaa5196dd26a46a1a16ceef8df5f39dc798e"

        def install
          bin.install "szero"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jadolg/szero/releases/download/v1.6.3/szero_Linux_arm64.tar.gz"
        sha256 "acdd6a1ce51e9c0b7d00f2687ebbb676dd7fe75ab512ee8c44a82a027bf56777"

        def install
          bin.install "szero"
        end
      end
    end
  end
end
