# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Szero < Formula
  desc "Temporarily scale down/up/restart all deployments in a namespace."
  homepage "https://github.com/jadolg/szero"
  version "1.6.10"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jadolg/szero/releases/download/v1.6.10/szero_1.6.10_darwin_amd64.tar.gz"
      sha256 "140a214efed4f14cabc6a058e810a9b4b5c60018b7197db209a06b7dce7d1515"

      def install
        bin.install "szero"
        bash_completion.install "completions/szero.bash" => "szero"
        zsh_completion.install "completions/szero.zsh" => "_szero"
        fish_completion.install "completions/szero.fish"
        man1.install "man/szero.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jadolg/szero/releases/download/v1.6.10/szero_1.6.10_darwin_arm64.tar.gz"
      sha256 "596b9fc738b4b1751d6ceaad3c371a82587a84930a66b06d65a1d33ff524008e"

      def install
        bin.install "szero"
        bash_completion.install "completions/szero.bash" => "szero"
        zsh_completion.install "completions/szero.zsh" => "_szero"
        fish_completion.install "completions/szero.fish"
        man1.install "man/szero.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jadolg/szero/releases/download/v1.6.10/szero_1.6.10_linux_amd64.tar.gz"
        sha256 "6d0a38a1809681fe219aaac52a376e0d5df22b88d088941b847bdb57523f64ab"

        def install
          bin.install "szero"
          bash_completion.install "completions/szero.bash" => "szero"
          zsh_completion.install "completions/szero.zsh" => "_szero"
          fish_completion.install "completions/szero.fish"
          man1.install "man/szero.1.gz"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jadolg/szero/releases/download/v1.6.10/szero_1.6.10_linux_arm64.tar.gz"
        sha256 "7dc37401723e3b759c5563d78e2fa6adf2e5d0a24e0747cd33df4884cd840dfd"

        def install
          bin.install "szero"
          bash_completion.install "completions/szero.bash" => "szero"
          zsh_completion.install "completions/szero.zsh" => "_szero"
          fish_completion.install "completions/szero.fish"
          man1.install "man/szero.1.gz"
        end
      end
    end
  end
end
